# Generated by Django 5.1.5 on 2026-03-04 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['apartment'], name='api_apartme_apartme_d2bf37_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['apartment'], name='api_notific_apartme_447e9d_idx'), models.Index(fields=['created_at'], name='api_notific_created_238c70_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.PositiveIntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='сом', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='due', max_length=16)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['apartment'], name='api_payment_apartme_1d1686_idx'), models.Index(fields=['status'], name='api_payment_status_632290_idx'), models.Index(fields=['due_date'], name='api_payment_due_dat_68ce3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.paymentcharge')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.PositiveIntegerField()),
                ('entrance', models.PositiveIntegerField()),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('is_payed', models.BooleanField(default=True)),
                ('is_accept', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['apartment'], name='api_profile_apartme_6f8db7_idx'), models.Index(fields=['apartment', 'entrance'], name='api_profile_apartme_625b7d_idx')],
            },
        ),
    ]
