# Generated by Django 5.1.5 on 2026-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcharge',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
