# Generated by Django 5.1.5 on 2026-03-04 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymentcharge_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.PositiveIntegerField()),
                ('entrance', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='due', max_length=16)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='paymentcharge',
            name='api_payment_apartme_1d1686_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentcharge',
            name='api_payment_status_632290_idx',
        ),
        migrations.RemoveField(
            model_name='paymentcharge',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='paymentcharge',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentcharge',
            name='status_updated_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymentparticipation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.paymentcharge'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.paymentparticipation'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipation',
            index=models.Index(fields=['apartment'], name='api_payment_apartme_fa4f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipation',
            index=models.Index(fields=['apartment', 'status'], name='api_payment_apartme_69ef56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipation',
            index=models.Index(fields=['status_updated_at'], name='api_payment_status__948ef8_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentparticipation',
            constraint=models.UniqueConstraint(fields=('payment', 'apartment'), name='uniq_payment_apartment'),
        ),
    ]
