# Generated by Django 5.1.5 on 2026-03-04 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentparticipation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentmember',
            options={'verbose_name': 'Пользователь квартиры', 'verbose_name_plural': 'Пользователи квартиры'},
        ),
        migrations.AlterModelOptions(
            name='devicepulse',
            options={'verbose_name': 'Состояние устройства', 'verbose_name_plural': 'Состояния устройств'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='paymentcharge',
            options={'verbose_name': 'Начисление', 'verbose_name_plural': 'Начисления'},
        ),
        migrations.AlterModelOptions(
            name='paymentparticipation',
            options={'verbose_name': 'Оплата (квартира)', 'verbose_name_plural': 'Оплаты (квартиры)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='apartment',
            field=models.PositiveIntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='apartmentmember',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='devicepulse',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно до'),
        ),
        migrations.AlterField(
            model_name='devicepulse',
            name='key',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='devicepulse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='apartment',
            field=models.PositiveIntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='currency',
            field=models.CharField(default='сом', max_length=16, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='paymentcharge',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='apartment',
            field=models.PositiveIntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='entrance',
            field=models.PositiveIntegerField(verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.paymentcharge', verbose_name='Начисление'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='status',
            field=models.CharField(choices=[('due', 'К оплате'), ('paid', 'Оплачено'), ('pending', 'На рассмотрении'), ('accepted', 'Принято')], default='due', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paymentparticipation',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Статус обновлён'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='apartment',
            field=models.PositiveIntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entrance',
            field=models.PositiveIntegerField(verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_accept',
            field=models.BooleanField(default=True, verbose_name='Подтверждён'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_payed',
            field=models.BooleanField(default=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.paymentparticipation', verbose_name='Оплата (квартира)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Загружено'),
        ),
    ]
