# Generated by Django 5.1.5 on 2026-03-04 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apartmentmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Push отправлен'),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Expo push token')),
                ('apartment', models.PositiveIntegerField(verbose_name='Квартира')),
                ('entrance', models.PositiveIntegerField(verbose_name='Подъезд')),
                ('platform', models.CharField(blank=True, default='', max_length=20, verbose_name='Платформа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Устройство (push)',
                'verbose_name_plural': 'Устройства (push)',
                'indexes': [models.Index(fields=['apartment'], name='api_pushdev_apartme_cb61f4_idx'), models.Index(fields=['is_active'], name='api_pushdev_is_acti_1eb66a_idx')],
            },
        ),
    ]
