# Generated by Django 5.1.5 on 2026-03-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_push_sent_at_pushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
    ]
