# Generated by Django 5.1.5 on 2026-04-04 09:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_has_parking_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            # На некоторых БД (особенно SQLite) индекс из старых миграций мог отсутствовать
            # (например, был удалён вручную). Следующие миграции могут пытаться его удалить
            # во время перестроения таблицы, поэтому гарантируем что он существует.
            sql="CREATE INDEX IF NOT EXISTS api_pushdev_token_t_d9f802_idx ON api_pushdevice (token_type);",
            reverse_sql="DROP INDEX IF EXISTS api_pushdev_token_t_d9f802_idx;",
        ),
        migrations.CreateModel(
            name='BuildingEntranceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.PositiveIntegerField(verbose_name='Подъезд')),
                ('apartment_from', models.PositiveIntegerField(verbose_name='Квартира от')),
                ('apartment_to', models.PositiveIntegerField(verbose_name='Квартира до')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Диапазон квартир (подъезд)',
                'verbose_name_plural': 'Диапазоны квартир (подъезды)',
            },
        ),
        migrations.CreateModel(
            name='ComplexBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(help_text='Идентификатор дома/блока в логине (например 20, 18, d).', max_length=16, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9]+$'), message='Только латиница/цифры без пробелов (например 20, 18, d)')], verbose_name='Дом/блок')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Название (опц.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Дом (ЖК)',
                'verbose_name_plural': 'Дома (ЖК)',
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Короткий код для логина (например EN, ART). Хранится в нижнем регистре.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z0-9]+$'), message='Только латиница/цифры без пробелов (например EN, ART)')], verbose_name='Код (латиница)')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'ЖК',
                'verbose_name_plural': 'ЖК',
            },
        ),
        migrations.RemoveConstraint(
            model_name='paymentparticipation',
            name='uniq_payment_apartment',
        ),
        migrations.AddField(
            model_name='buildingentrancerange',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_ranges', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='apartmentmember',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartment_members', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='notification',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='paymentcharge',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Если заполнено — начисление видят только жители этого дома.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_charges', to='api.complexbuilding', verbose_name='Дом (опц.)'),
        ),
        migrations.AddField(
            model_name='paymentparticipation',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_participations', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='push_devices', to='api.complexbuilding', verbose_name='Дом'),
        ),
        migrations.AddIndex(
            model_name='apartmentmember',
            index=models.Index(fields=['building', 'apartment'], name='api_apartme_buildin_7cfdad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentparticipation',
            index=models.Index(fields=['building', 'apartment'], name='api_payment_buildin_f28630_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['building', 'apartment'], name='api_pushdev_buildin_82717a_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentparticipation',
            constraint=models.UniqueConstraint(fields=('payment', 'building', 'apartment'), name='uniq_payment_building_apartment'),
        ),
        migrations.AddIndex(
            model_name='residentialcomplex',
            index=models.Index(fields=['slug'], name='api_residen_slug_c6b372_idx'),
        ),
        migrations.AddField(
            model_name='complexbuilding',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='api.residentialcomplex', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='notification',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='api.residentialcomplex', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='paymentcharge',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_charges', to='api.residentialcomplex', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='profile',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='api.residentialcomplex', verbose_name='ЖК'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['complex', 'building', 'apartment'], name='api_notific_complex_3216a0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcharge',
            index=models.Index(fields=['complex', 'building'], name='api_payment_complex_bd498d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['complex', 'building'], name='api_profile_complex_09443f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['complex', 'building', 'apartment', 'entrance'], name='api_profile_complex_55d755_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingentrancerange',
            index=models.Index(fields=['building', 'entrance'], name='api_buildin_buildin_1be0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingentrancerange',
            index=models.Index(fields=['building', 'apartment_from', 'apartment_to'], name='api_buildin_buildin_ce2b96_idx'),
        ),
        migrations.AddIndex(
            model_name='complexbuilding',
            index=models.Index(fields=['complex', 'building_id'], name='api_complex_complex_0497b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='complexbuilding',
            constraint=models.UniqueConstraint(fields=('complex', 'building_id'), name='uniq_complex_building_id'),
        ),
    ]
