# Generated by Codex on 2026-04-04

from __future__ import annotations

import re
from typing import Any

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


OLD_USERNAME_RE = re.compile(r"^(?P<apartment>\d+)-(?P<entrance>\d+)$")
SPLIT_RE = re.compile(
    r"^(?P<complex>[a-z0-9]+)-(?P<building>[0-9]+|[a-z]+)-(?P<entrance>\d+)-(?P<apartment>\d+)$",
    re.IGNORECASE,
)


def _normalize_complex_slug(value: str) -> str:
    return (value or "").strip().lower()


def _normalize_building_id(value: str) -> str:
    v = (value or "").strip().lower()
    if v.isdigit():
        v = str(int(v))
    return v


def _settings_cfg() -> dict[str, Any]:
    cfg = getattr(settings, "DBN_COMPLEXES", None)
    return cfg if isinstance(cfg, dict) else {}


def _seed_from_settings(apps):
    ResidentialComplex = apps.get_model("api", "ResidentialComplex")
    ComplexBuilding = apps.get_model("api", "ComplexBuilding")
    BuildingEntranceRange = apps.get_model("api", "BuildingEntranceRange")

    cfg = _settings_cfg()
    for c_slug_raw, c_cfg in cfg.items():
        c_slug = _normalize_complex_slug(str(c_slug_raw))
        if not c_slug:
            continue
        title = str((c_cfg or {}).get("title") or c_slug.upper())
        complex_obj, _ = ResidentialComplex.objects.get_or_create(slug=c_slug, defaults={"title": title})
        if complex_obj.title != title and title:
            ResidentialComplex.objects.filter(id=complex_obj.id).update(title=title)

        buildings = (c_cfg or {}).get("buildings") or {}
        if not isinstance(buildings, dict):
            continue
        for b_id_raw, b_cfg in buildings.items():
            b_id = _normalize_building_id(str(b_id_raw))
            if not b_id:
                continue
            building_obj, _ = ComplexBuilding.objects.get_or_create(
                complex_id=complex_obj.id,
                building_id=b_id,
                defaults={"title": ""},
            )

            ranges = (b_cfg or {}).get("entrance_ranges") or []
            for ent, start, end in ranges:
                try:
                    ent_i = int(ent)
                    start_i = int(start)
                    end_i = int(end)
                except Exception:
                    continue
                BuildingEntranceRange.objects.get_or_create(
                    building_id=building_obj.id,
                    entrance=ent_i,
                    apartment_from=start_i,
                    apartment_to=end_i,
                )


def _ensure_default_complex(apps):
    ResidentialComplex = apps.get_model("api", "ResidentialComplex")
    ComplexBuilding = apps.get_model("api", "ComplexBuilding")

    cx = ResidentialComplex.objects.order_by("slug").first()
    if not cx:
        cx = ResidentialComplex.objects.create(slug="default", title="Default")
    b = ComplexBuilding.objects.filter(complex_id=cx.id).order_by("building_id").first()
    if not b:
        b = ComplexBuilding.objects.create(complex_id=cx.id, building_id="1", title="")
    return cx, b


def _build_lookup(apps):
    ResidentialComplex = apps.get_model("api", "ResidentialComplex")
    ComplexBuilding = apps.get_model("api", "ComplexBuilding")

    complexes = list(ResidentialComplex.objects.all().order_by("slug"))
    buildings = list(ComplexBuilding.objects.select_related("complex").all().order_by("complex__slug", "building_id"))
    buildings_by_complex: dict[str, list[str]] = {}
    for b in buildings:
        buildings_by_complex.setdefault(str(b.complex.slug), []).append(str(b.building_id))
    return complexes, buildings_by_complex


def _parse_username_to_scope(username: str, complexes: list, buildings_by_complex: dict[str, list[str]]):
    raw = (username or "").strip()
    if not raw:
        return None, None

    m = SPLIT_RE.match(raw)
    if m:
        return _normalize_complex_slug(m.group("complex")), _normalize_building_id(m.group("building"))

    if OLD_USERNAME_RE.match(raw):
        return None, None

    raw_l = raw.lower()
    complex_slugs = [str(c.slug) for c in complexes]
    for slug in sorted(complex_slugs, key=len, reverse=True):
        if not raw_l.startswith(slug):
            continue
        rest = raw_l[len(slug) :].strip()
        if not rest:
            return slug, None
        building_ids = buildings_by_complex.get(slug) or []
        for b_id in sorted(building_ids, key=len, reverse=True):
            if rest.startswith(b_id):
                return slug, b_id
        return slug, None

    return None, None


def seed_and_backfill(apps, schema_editor):
    _seed_from_settings(apps)
    default_complex, default_building = _ensure_default_complex(apps)

    ResidentialComplex = apps.get_model("api", "ResidentialComplex")
    ComplexBuilding = apps.get_model("api", "ComplexBuilding")
    Profile = apps.get_model("api", "Profile")
    ApartmentMember = apps.get_model("api", "ApartmentMember")
    PushDevice = apps.get_model("api", "PushDevice")
    Notification = apps.get_model("api", "Notification")
    PaymentCharge = apps.get_model("api", "PaymentCharge")
    PaymentParticipation = apps.get_model("api", "PaymentParticipation")
    User = apps.get_model("auth", "User")

    complexes, buildings_by_complex = _build_lookup(apps)

    # Profiles: по username (если возможно), иначе дефолт.
    user_ids = list(Profile.objects.values_list("user_id", flat=True))
    user_map = {u.id: u.username for u in User.objects.filter(id__in=user_ids).only("id", "username")}
    for p in Profile.objects.select_related("user").all().only("id", "user_id", "complex_id", "building_id"):
        if p.complex_id and p.building_id:
            continue
        username = user_map.get(p.user_id, "") or ""
        c_slug, b_id = _parse_username_to_scope(username, complexes, buildings_by_complex)

        cx = default_complex
        if c_slug:
            cx = ResidentialComplex.objects.filter(slug=str(c_slug)).first() or default_complex

        b = default_building
        if b_id:
            b = ComplexBuilding.objects.filter(complex_id=cx.id, building_id=str(b_id)).first() or default_building
        else:
            b = ComplexBuilding.objects.filter(complex_id=cx.id).order_by("building_id").first() or default_building

        Profile.objects.filter(id=p.id).update(complex_id=cx.id, building_id=b.id)

    # Остальные таблицы: старые записи считаем дефолтными.
    ApartmentMember.objects.filter(building__isnull=True).update(building_id=default_building.id)
    PushDevice.objects.filter(building__isnull=True).update(building_id=default_building.id)
    PaymentParticipation.objects.filter(building__isnull=True).update(building_id=default_building.id)
    Notification.objects.filter(complex__isnull=True).update(complex_id=default_complex.id)
    PaymentCharge.objects.filter(complex__isnull=True).update(complex_id=default_complex.id)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_buildingentrancerange_complexbuilding_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="complex",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="profiles", to="api.residentialcomplex", verbose_name="ЖК"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="building",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="profiles", to="api.complexbuilding", verbose_name="Дом"),
        ),
        migrations.AlterField(
            model_name="apartmentmember",
            name="building",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="apartment_members", to="api.complexbuilding", verbose_name="Дом"),
        ),
        migrations.AlterField(
            model_name="pushdevice",
            name="building",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="push_devices", to="api.complexbuilding", verbose_name="Дом"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="complex",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications", to="api.residentialcomplex", verbose_name="ЖК"),
        ),
        migrations.AlterField(
            model_name="paymentcharge",
            name="complex",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_charges", to="api.residentialcomplex", verbose_name="ЖК"),
        ),
        migrations.AlterField(
            model_name="paymentparticipation",
            name="building",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_participations", to="api.complexbuilding", verbose_name="Дом"),
        ),
    ]

