# Generated by Django 5.1.5 on 2026-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_seed_complexes_and_backfill_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пароль сменён'),
        ),
    ]
